# Generated by Django 5.2.6 on 2025-12-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaclinica',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
